name: Build

on:
  workflow_run:
    workflows: ["Go Test", "Next.js Lint and Test"]
    branches:
      - "*"
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    needs: ["test", "lint-and-test"]

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.1'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Run Build
        run: make build